[tool.poetry]
name = "couckoo"
version = "0.1.0"
description = ""
authors = ["Muftawo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
imagehash = "^4.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
